### ISSUE TITLE
В Build-версии не отображаются векторные изображения

### ISSUE THREAD

**Issue by jellySWATy** [FARCER/gulp4start#1]
В Build-версии не отображаются векторные изображения

**Comment by FARCER** [comment]
На локале или на сервере? На локале могут не отображаться из-за того, что так настроен браузер

**Comment by jellySWATy** [comment]
На локале. Я так понимаю что просто нужно на какой-либо сервер загрузить (по крайней мере на Open Server все заработало)

**Comment by FARCER** [comment]
Да, все верно.  На сервере все работает отлично
